### ISSUE TITLE
Device won't boot if flashed to emmc

### ISSUE THREAD

**Issue by TimotheeLF** [nikhiljha/pp-fedora-sdsetup#10]
In my experience, the pinephone will not boot to fedora if the OS is flashed to the emmc through jumpdrive. 
I get a black screen with a green LED.

**Comment by nikhiljha** [comment]
Yeah, there's a script that needs to be run to detect if it's on the emmc or on the sd card. Needs to be added to `boot.cmd`.

**Comment by stevenvandenbrandenstift** [comment]
see commit cd03c40a103ae224b8070dadb19b21cb20a3b666 and fa8963fc72f1e10cd6c7431f8a40c4ddb5c361e. One can use the released image, flash that via jumpdrive on the emmc, and then replace the boot.scr and the /etc/fstab file.
@nikhiljha I suppose this can now be closed.

**Comment by nikhiljha** [comment]
👍 I’ll close it once I have a released image and I’ve tested everything

**Comment by stevenvandenbrandenstift** [comment]
tested latest release and it works very well.
