### ISSUE TITLE
micro isn't working anymore.

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#100]
Pipewire updates from 8.2. or a kernel update seem to have broken audio mic support.

Besides glib2 2.67.3 crashing pulse and pipewire , even a downgrade back to 31.1. for gstreamer,pipewire,alsa and pulse did not bring mic sound back. 

Can you verify this on another installation?

**Comment by alh61** [comment]
Audio was indeed a mess for a time. Isn't it fixed now ?

**Comment by Cyborgscode** [comment]
this is indeed fixed in actual alsa & pipewire packages.
