### ISSUE TITLE
Screen turns off after booting up

### ISSUE THREAD

**Issue by Archehandoro** [nikhiljha/pp-fedora-sdsetup#101]
Hello,

I just installed the latest fedora image in the PinePhone, via JumpDrive directly in the eMMC.

After booting up, in a matter of few seconds, the screen turns off. The Phone remains on, and I can connect to it via ssh. However, when running dnf -to see whether there are any updates that could fix the issue- dnf outputs: 

`Curl error (23): Failed writing received data to disk/application for http://mirror.bytemark.co.uk/fedora/linux/development/rawhide/Everything/aarch64/os/Packages/l/linux-firmware-20210208-117.fc34.noarch.rpm [Failure writing output to destination]`

I have tried to run `rpm -Va` but aside of show missing packages it doesn't return any failures.

Any ideas on the issue or any tips that would help me troubleshoot?

Thanks!

**Comment by Torbuntu** [comment]
As far as the screen blanking, have you checked that auto brightness is disabled in settings? If you shine a flashlight at the screen can you see if something is in fact on? This is something that should be disabled in a future version, because it is super annoying.

**Comment by Archehandoro** [comment]
Yes, you're right. Auto brightnes was on, I have managed to disable it and it seems working now.

Now that I can see the screen, the issue with dnf seems to be related a lack of space in root. I'll have a look a that. Thanks for your help!

**Comment by nikhiljha** [comment]
The lack of space is because the root partition needs to be manually resized, see the install instructions in https://github.com/nikhiljha/pp-fedora-sdsetup/releases
