### ISSUE TITLE
No Root Memory Available

### ISSUE THREAD

**Issue by Braillynn** [nikhiljha/pp-fedora-sdsetup#104]
Upon flashing and trying to update the OS through terminal on a 3GB PinePhone, the update fails and states no root memory/storage available.

**Comment by Torbuntu** [comment]
Did you make sure to resize the rootfs before inserting into the pinephone?

**Comment by nikhiljha** [comment]
Here are the instructions again, (from your computer, not from the PinePhone). Automatic resize is something that we want though! Would welcome contributions.

    sudo parted /dev/<your_sd_card_device>
    (parted) resizepart 2 100%
    (parted) quit
    sudo resize.f2fs /dev/<the_second_sd_card_PARTITION>
