### ISSUE TITLE
rpm-ostree / Silverblue support

### ISSUE THREAD

**Issue by BobyMCbobs** [nikhiljha/pp-fedora-sdsetup#105]
I'd like to run Silverblue on a Pinephone.
Are there any thoughts around running it?

I understand that some folks have managed to migrate from a standard workstation install to Silverblue.

**Comment by nikhiljha** [comment]
Hi! Quite a few people have brought this up, and it could be a good idea! The consensus was that we probably won't be looking into this, at least until the main PinePhone Kernel Patches and all useful software are packaged and upstream.

Closing for now, but thanks!
