### ISSUE TITLE
Download script fails looking for 5.9 kernel

### ISSUE THREAD

**Issue by ikidd** [nikhiljha/pp-fedora-sdsetup#106]
Fixed to 5.12 in URL, seems to go.

**Comment by alh61** [comment]
I assume you are talking about the script files to create an image yourself. These scripts are indeed far behind reality;
we can only hope torbuntu finds time to update them.

**Comment by alh61** [comment]
I assume you are talking about the script files to create an image yourself. These scripts are indeed far behind reality;
we can only hope torbuntu finds time to update them.
