### ISSUE TITLE
Phosh Torch toggle doesn't do anything

### ISSUE THREAD

**Issue by J3RN** [nikhiljha/pp-fedora-sdsetup#108]
I'm using the latest release (Release 9, March 22). Open the Phosh quick control menu and tapping the torch icon doesn't do anything. I can try to dig into this on my own, but I'm a web dev so it's hard to say if I'll get anywhere :sweat_smile:

**Comment by Torbuntu** [comment]
It hasn't been implemented yet in Phosh. There is an outstanding MR to have it wired up somewhere.

**Comment by Torbuntu** [comment]
This is now working in the latest fedora phosh package.
