### ISSUE TITLE
Newbie questions and  feedback using Fedora on the PinePhone

### ISSUE THREAD

**Issue by skeydan** [nikhiljha/pp-fedora-sdsetup#113]
Hi,

I'm apologizing in advance if this is a bad place for the below questions & user feedback. If it is, can you let me know what would be a better one?
I've tried the Pine forum (https://forum.pine64.org/showthread.php?tid=14995), but not gotten any response (it seems like Fedora is not so often used on the PinePhone).

For context, I just got my first PinePhone, and am using Megi's multi-distro image for experimentation.
I've run dnf update, which if I understand correctly does not update the kernel. But everything else should be up-to-date.

Questions/experiences:

1) Using the Settings application, I have to often switch manually between landscape and portrait orientations in order to be able to close sub-windows. I do this by leaving Settings and clicking on the portrait/landscape icon. Is there a way around this?

2) Just be be sure - the display is not supposed to be switching between orientations itself when I rotate the phone, right?

3) Again just to be sure - there is just one possible screen resolution; that's to be expected too, I guess?

4) BTW, "portrait" and "landscape" are the other way round, for me ...

5) Using Calls, the sound level is extremely low (practically unhearable). This is despite system-wide, sound is set to maximum.

6) I was expecting I had to enter the PIN on startup, but I've found it's instead configured in the "Mobile Broadband" settings. Isn't this a security problem (assuming someone could log into my phone)?

7) After a phone reboot, I always have to actively turn on Mobile Broadband - is this expected?

8) Is there a roadmap for the project?

9) Would  you recommend Fedora for "production use" on the PinePhone?

Many thanks in advance!!

**Comment by Torbuntu** [comment]
> using Megi's multi-distro image for experimentation.

I don't know which version that would be, but I'm going to guess it is much older than the one we have here. It is also possible that the image uses an old enough version to be on a previous release of Fedora altogether. We are currently running on Fedora Rawhide 36.

1,2: rotation should be handled automatically now. Sounds like the image on the multi boot image doesn't have the hostname set to handset. You can check with `hostnamectl` and `Chassis` should say `handset`. You can also use hostnamectl to set chassis handset if you'd like.

3: I see in Settings -> Display quite a few options for resolution scaling (100, 125, 150, 175 etc...) So, again, check to make sure you're on Fedora Rawhide 36. 


8: https://fedoraproject.org/wiki/Mobility <- Good place to get information. 

I would also recommend reaching out directly to our chat platforms: https://fedoraproject.org/wiki/Mobility#Communication where we an answer question as well.

9. I would not recommend any PinePhone distribution for "production use", personally. However, I daily drive Fedora on my PinePhone as my only phone, with all the issues. 

Hope this helps :)

**Comment by skeydan** [comment]
Thanks so much @Torbuntu !!

That is extremely helpful! I'll make sure I install the up-to-date distribution, and test all the above things again. 

I can update this issue with what I find, but if you prefer closing it, please go ahead and do so :-)

>I would not recommend any PinePhone distribution for "production use", personally. However, I daily drive Fedora on my PinePhone as my only phone, with all the issues.

Well, "production use" was not quite the correct word ;-) ... I'm super happy it's stable enough for normal use, - I was going to try one of the more frequently-used distros "for real" first but now I've changed my mind ... :-)

**Comment by Torbuntu** [comment]
I'll close this for now and if you have other issues with the latest version of stuff you can always feel free to post them.

Otherwise if you'd like quicker feedback I do recommend the chats as there are more eyes in them.
