### ISSUE TITLE
Fresh install fails updates: pinephone-helper package version file collisions

### ISSUE THREAD

**Issue by greg-hellings** [nikhiljha/pp-fedora-sdsetup#114]
On a fresh install running `sudo dnf update -y` results in two different versions of pinephone-helper having collisions.

Uninstalling the existing version allows the update to proceed.

**Comment by Torbuntu** [comment]
Yeah I really botched that package update... sorry about that. I'll try and get a new image out soon with the latest updates already set.

**Comment by Torbuntu** [comment]
https://github.com/nikhiljha/pp-fedora-sdsetup/releases/tag/v0.7.0
