### ISSUE TITLE
Can't Update Software

### ISSUE THREAD

**Issue by psppwner300** [nikhiljha/pp-fedora-sdsetup#12]
Trying to run
`sudo dnf update`
In the terminal lists a bunch of packages to upgrade, but the phone warns me of low disk space and will stop abruptly while updating. I have the OS flashed on a 128 GB SD card. How can I increase the disk space so I have enough space to upgrade?

**Comment by nikhiljha** [comment]
Ideally this is done from a separate (not-pinephone) computer. Make sure you're using the interactive `parted` (the second and third commands only work inside parted, not inside your shell).

```
sudo parted /dev/<your_sd_card_device>
(parted) resizepart 2 100%
(parted) quit
sudo resize /dev/<the_second_sd_card_PARTITION>
```

**Comment by nikhiljha** [comment]
This has been documented in the releases page, closing. Let me know if you need any more help :)
