### ISSUE TITLE
After updating Phosh shows no icons except Firefox and Power Statistics

### ISSUE THREAD

**Issue by carlmo** [nikhiljha/pp-fedora-sdsetup#125]
When I first installed the latest release for Pinephone [1], the Phosh icons were correctly showed.

After updating, I don't see most icons, see picture attached

[1] [Release #11: Dec 15, 2021](https://github.com/nikhiljha/pp-fedora-sdsetup/releases/tag/v0.6.0)

**Comment by carlmo** [comment]
![signal-2022-08-22-214130](https://user-images.githubusercontent.com/14909968/186049993-f2a32077-0f88-4dfa-b6d0-1edd9697a1e3.jpeg)

**Comment by Torbuntu** [comment]
Please try the latest image and be aware these are for testing purposes and not intended for daily usage. https://github.com/nikhiljha/pp-fedora-sdsetup/releases/tag/v0.7.0

**Comment by carlmo** [comment]
Newest image worked just fine. Thanks
