### ISSUE TITLE
volume buttons do nothing

### ISSUE THREAD

**Issue by Torbuntu** [nikhiljha/pp-fedora-sdsetup#15]
It seems the volume buttons do not change volume at all.

**Comment by thibaultamartin** [comment]
@Torbuntu IIRC you have a partial answer to that too

**Comment by Torbuntu** [comment]
Same as the other issue, which may or may not be related.

I did find out that in GNOME on Xorg the volume buttons behave as expected and adjust the system volume.

**Comment by janbrummer** [comment]
Well, it's not there yet: https://source.puri.sm/Librem5/phosh/-/issues/308

Does not make sense to track this one here.
