### ISSUE TITLE
Drop obsolete gschema mobile-user-agent=true

### ISSUE THREAD

**Issue by janbrummer** [nikhiljha/pp-fedora-sdsetup#19]
```
[org.gnome.Epiphany.web]
mobile-user-agent=true

```
Is obsolete and has been replaced by chassis detection. Only if chassis is set to handset the mobile user agent is set as identification.

Therefore you need to ensure that: `hostnamectl status` returns handset as chassis.

You can set it through:
`hostnamectl set-chassis handset`

**Comment by nikhiljha** [comment]
https://github.com/nikhiljha/pp-fedora-sdsetup/commit/64d1698f467f68e5224531f27daccc9c41ed9448
