### ISSUE TITLE
gnome-software is unusable

### ISSUE THREAD

**Issue by e-minguez** [nikhiljha/pp-fedora-sdsetup#23]
It doesn't fit the screen so you cannot install anything. I guess it misses a few patches such as https://gitlab.com/mobian1/packages/gnome-software/-/commit/314e7725551e8d33f4e501bef6a9fe8ecac097ff

**Comment by Torbuntu** [comment]
With phoc 0.4.0 and the `scale-to-fit` gnome-software becomes usable (after configuring it)
This should be coming in a `dnf upgrade` shortly once it gets to the mirrors.
