### ISSUE TITLE
More detailed first steps

### ISSUE THREAD

**Issue by richardanaya** [nikhiljha/pp-fedora-sdsetup#25]
Just wanted to say this is an awesome project!

I really enjoyed this distro and could do a lot of things, 

I feel like new users could use some more detailed instructions

1. download
2. `sudo dnf install liveusb-creator zstd gparted`
3. `zstd -d pp-fedora-20200615.img.zst -o pp-fedora-20200615.img`
4. `mediawriter` and burn `pp-fedora-20200615.img` to microsd
5. use `gparted` to resize microsd so that partition takes up full space
6. turn off phone and take off back of phone
7. place SD card in slot below switches
8. turn on phone
9. type 1111 as password ( this is also sudo password )

**Comment by nikhiljha** [comment]
Just going through old issues - instructions have been in https://github.com/nikhiljha/pp-fedora-sdsetup/releases for a while.
