### ISSUE TITLE
Can't unlock phosh with default password

### ISSUE THREAD

**Issue by subpop** [nikhiljha/pp-fedora-sdsetup#26]
## Description

When phosh locks the screen after an idle timeout, entering the default password (`1111`) does not unlock. The "Checking" label shakes, indicating the password failed.

## Steps to Reproduce

1. Flash v0.1.0 and boot
2. Log in via lightdm (the green numbers) with the default password (`1111`)
3. Wait for the shell to lock the screen
3. Enter the default password to unlock

## Expected Results

The shell should unlock the session and present the launcher.

## Actual Results

The shell does not unlock.

## Additional Information

After changing the password to something else, the lock screen *does* unlock after entering the new password.

**Comment by Torbuntu** [comment]
Did this happen again after reflashing?

If so, could you find anything in the logs?

**Comment by ScardracS** [comment]
I have tried it yesterday and now problems at all

**Comment by subpop** [comment]
I've flashed it multiple times since first experiencing this and I cannot reproduce it again. Must have been a fluke.
