### ISSUE TITLE
Running "# dnf update" locks device in kernel boot step

### ISSUE THREAD

**Issue by zenyuk** [nikhiljha/pp-fedora-sdsetup#27]
device:
pine64 UBPortsEdition

using
Release #5: June 15, 2020
https://github.com/nikhiljha/pp-fedora-sdsetup/releases/tag/v0.1.0

installed on eMMC

run
"# dnf update"

result:
pinephone reboots and hangs in kernel loading
(sorry don't have screenshot with actual step)

**Comment by nikhiljha** [comment]
Yeah... the image is kinda broken right now. Sorry about that :(

We're doing a bunch of things upstream to get this working soon (TM).

**Comment by ScardracS** [comment]
I have tried it running # dnf update --nogpgcheck and same with upgrade. No errors at all (the only thing is grub2 that doesn't update but we don't need it at all)

**Comment by Torbuntu** [comment]
Note, this image uses rawhide fedora. And recently Fedora 33 was branched. This means rawhide is required to import the new gpg key for fedora 34.
`sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-34-primary`
