### ISSUE TITLE
Fails to install kernel with script

### ISSUE THREAD

**Issue by ScardracS** [nikhiljha/pp-fedora-sdsetup#28]
Running script fails to install kernel package

"No match for argument: kernel
Error: Unable to find a match: kernel"

**Comment by Torbuntu** [comment]
The kernel package was renamed to "megi-kernel-bh" and "megi-kernel-ce". 

You'll want to install the correct one from those (bh for braveheart ce for community edition). Then just remove the old kernel package.

**Comment by ScardracS** [comment]
Thanks for the correction
