### ISSUE TITLE
Self compiled image can't access Phosh

### ISSUE THREAD

**Issue by ScardracS** [nikhiljha/pp-fedora-sdsetup#29]
Hi,

I have successfully compiled and it boot but when I try to unlock and put my pin it doesn't do anything, it just remain on PIN lock screen.

Any idea?

**Comment by Torbuntu** [comment]
I'm also having this problem. It will usually drop to a flashing cursor on a blank screen for me as well.

**Comment by ScardracS** [comment]
> I'm also having this problem. It will usually drop to a flashing cursor on a blank screen for me as well. 

On my side it show the lock screen but put the pin doesn't make anything

**Comment by Torbuntu** [comment]
After I put in the pin it takes a good couple minutes before it bombs. Yesterday I somehow magically got a successful couple of sign ins, but not today yet.

I also upgraded my kernel and removed grub2. But that was yesterday when I was able to boot.

**Comment by ScardracS** [comment]
> I'm also having this problem. It will usually drop to a flashing cursor on a blank screen for me as well. 

I'm watching on it. If I will find something I will report it

**Comment by Torbuntu** [comment]
```
Aug 06 19:23:05 fedora-pinephone dbus-daemon[1268]: [session uid=990 pid=1266] Activating service name='org.freedesktop.systemd1' requested by ':1.2' (uid=990 pid=1275 comm="/usr/bin/dbus-broker-launch --config-file=/usr/sha")
Aug 06 19:23:05 fedora-pinephone dbus-daemon[1268]: [session uid=990 pid=1266] Activated service 'org.freedesktop.systemd1' failed: Process org.freedesktop.systemd1 exited with status 1
Aug 06 19:23:05 fedora-pinephone dbus-broker-launch[1275]: Activation request for 'org.a11y.atspi.Registry' failed.
Aug 06 19:26:00 fedora-pinephone lightdm[1283]: gkr-pam: unable to locate daemon control file
Aug 06 19:26:00 fedora-pinephone lightdm[1283]: gkr-pam: stashed password to try later in open session
Aug 06 19:26:34 fedora-pinephone lightdm[1253]: pam_unix(lightdm-greeter:session): session closed for user lightdm
```
I was *finally* able to login and I found these monsters using `journalctl -e -b 0 -p 3`

**Comment by ScardracS** [comment]
I did it! You should put a 8 number password ![IMG_20200818_190615.jpg](https://user-images.githubusercontent.com/12005889/90543400-f117f300-e185-11ea-9c5f-edccc1c01c8a.jpg)

**Comment by ScardracS** [comment]
I have uploaded my repo here: https://github.com/ScardracS/Fedora-for-PinePhone and img here: https://mega.nz/file/YWASgCxQ#9CCdNHwxD85Rx_i3QfMZAUHoKtVm4BwP5D3508_nL7E

**Comment by ScardracS** [comment]
Password is 12345678

**Comment by Torbuntu** [comment]
Where is that being set?

**Comment by ScardracS** [comment]
New bug: after a reboot the device can't access phosh anymore, only gnome works
