### ISSUE TITLE
Download fails

### ISSUE THREAD

**Issue by RossComputerGuy** [nikhiljha/pp-fedora-sdsetup#3]
```
--2020-02-24 13:10:46--  https://dl.fedoraproject.org/pub/fedora-secondary/development/rawhide/Workstation/aarch64/images/Fedora-Workstation-Rawhide-20200218.n.0.aarch64.raw.xz
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving dl.fedoraproject.org (dl.fedoraproject.org)... 209.132.181.24, 209.132.181.25, 209.132.181.23
Connecting to dl.fedoraproject.org (dl.fedoraproject.org)|209.132.181.24|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-24 13:10:46 ERROR 404: Not Found
```

**Comment by Torbuntu** [comment]
That part of the script needs manual intervention for collecting the correct version of rawhide. 
The script is pointing at an older 20200218 version, but if you go to the images/ directory in the url you see the newest file is now Fedora-Workstation-Rawhide-20200224.n.0.aarch64.raw.xz  

it could be possible to get close to fixing this by modifying the date string in Bash to use "today's" date in the correct format. But even that has no guarantee of being accurate given the timezone and upload dates.

**Comment by nikhiljha** [comment]
I added a warning with the above information. Leaving this issue open until it automatically grabs the right file name.

**Comment by Rafostar** [comment]
@nikhiljha 
I made a PR that should solve this issue.
