### ISSUE TITLE
Could not resolve copr on script

### ISSUE THREAD

**Issue by ScardracS-zz** [nikhiljha/pp-fedora-sdsetup#30]
Hi,

do you have same error when enabling copr repo?

curl error (6): Couldn't resolve host name for https://copr.fedorainfracloud.org/coprs/njha/mobile/repo/fedora-rawhide/dnf.repo?arch=aarch64 [Could not resolve host: copr.fedorainfracloud.org]

I have tried opening it on firefox and with curl works but dnf doesn't

**Comment by Torbuntu** [comment]
Are you trying to enable it during build steps using chroot qemu-aarch64-static? You'll need to copy the host `/etc/resolv.conf`

**Comment by ScardracS** [comment]
> Are you trying to enable it during build steps using chroot qemu-aarch64-static? You'll need to copy the host `/etc/resolv.conf`

The error born here https://github.com/nikhiljha/pp-fedora-sdsetup/blob/master/phone-scripts/02-install-packages.sh

Since yesterday there wasn't any error and I haven't changed anything on my side

**Comment by Torbuntu** [comment]
Strange, for the last week or 2 since I started trying to build with this I've had no choice but to copy the /etc/resolv.conf to make it work.

**Comment by ScardracS** [comment]
> Strange, for the last week or 2 since I started trying to build with this I've had no choice but to copy the /etc/resolv.conf to make it work.

I don't really know why but I haven't to

**Comment by ScardracS** [comment]
EDIT

cp /etc/resolv.conf rootfs/etc/resolv.conf fix the issue as told by @Torbuntu but that's strange as I haven't that problem before

**Comment by alvaropg** [comment]
> EDIT
> 
> cp /etc/resolv.conf rootfs/etc/resolv.conf fix the issue as told by @Torbuntu but that's strange as I haven't that problem before

Same issue here. Looks that there is a broken symlink:

rootfs/etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf

**Comment by Torbuntu** [comment]
It is due to a change in Fedora33 using `systemd-resolved`
https://fedoraproject.org/wiki/Changes/systemd-resolved

**Comment by nikhiljha** [comment]
Fixed in newest release!
