### ISSUE TITLE
move camera drivers to kernel

### ISSUE THREAD

**Issue by ScardracS-zz** [nikhiljha/pp-fedora-sdsetup#43]
As shown on Arch Linux ARM, move camera drivers directly on kernel make linux-firmware unuseful (and it takes 264MB of spaces)

I would like to suggest to consider this fact and port it on this/next kernel

**Comment by Cyborgscode** [comment]
is it megapixels problem that cams do not with with kernel 5.10?

**Comment by alh61** [comment]
afaik all drivers are in kernel and megapixels work now - so yes, linux-firmware is not needed anymore. We can close this bug.
