### ISSUE TITLE
Fresh image build from the scripts results in working sdcard, but fail to boot when on emmc

### ISSUE THREAD

**Issue by DavidHaltinner** [nikhiljha/pp-fedora-sdsetup#50]
Using today's current rawhide. I have a 3gb phone so I stole the uboot binary from postmarketos to replace the one the scripts used. I also modified the scripts to change the user, add my local nameserver to the qemu chroot, but nothing major.

Image works perfectly fine off of sdcard, no issues noted, runs great.

So I installed it to the emmc. Uboot, fine, loads kernel and starts loading services, but fails at dbus (which causes multiple other things to fail). only error I found is:
Unable to open service directory '/usr/share/dbus-1/system-service directory '/usr/share/dbus-1/system-services': "Invalid argument"
Which doesnt seem to make sense when looking at how dbus was launched in the .service file. Nor does it make sense as to why it works off the sdcard fine, but not the emmc.
I thought Id post as an issue in case it has something to do with the boot.scr and what follows, since I am not too familiar with that piece. But it could be an upstream issue too, but then why ok on the sd card?

**Comment by elajoie** [comment]
Use this to write uboot to emmc or sdcard
ftp://ftp.warpspeed.dk/PinePhone/u-boot.zip

**Comment by Torbuntu** [comment]
Current rawhide from this github releases, or the official rawhide from Fedora itself?

**Comment by DavidHaltinner** [comment]
Fedora itself. I didnt use the image from june released here, i just used the scripts to pull the current rawhide from Fedora.

**Comment by DavidHaltinner** [comment]
> Use this to write uboot to emmc or sdcard
> ftp://ftp.warpspeed.dk/PinePhone/u-boot.zip
> 
> Join Discord/Telegram/irc if you want to catch up with the author _Yoda
> 
> And here is his Kernel script for latest:
> ftp://ftp.warpspeed.dk/PinePhone/Multikernel-scripts.zip

I have had no issues with uboot, the one i used worked fine for the 3gb phone. Im not sure how uboot would effect dbus when only on emmc?

**Comment by Torbuntu** [comment]
Even wifi and networking works with the vanilla fedora rawhide? (Using postmarketOS uboot)?

**Comment by DavidHaltinner** [comment]
wifi works just fine, i didnt try cellular data yet though.

**Comment by DavidHaltinner** [comment]
They add two patches to the base code, but nothing weird, no odd configuration options. i just stole theirs because i was too lazy to compile it myself, i didnt see anything weird about how they do it, i suspect it should be just fine, but i can compile it on the fedora sd card too. i didnt think that uboot would effect dbus.
Their apk build: https://gitlab.com/postmarketOS/pmaports/-/blob/master/temp/u-boot-pinephone/APKBUILD

**Comment by Torbuntu** [comment]
Huh... And you are using the Fedora Kernel as well? Or is that also from somewhere else? When I tried the fedora image (and fedora uboot) it didn't have networking.

**Comment by DavidHaltinner** [comment]
The one that the scripts pull, appears to be megi (uname on the phone says 5.9 rc1), and it pulls fom the copr repo in the scripts and according to his spec file its from megi's.

**Comment by Torbuntu** [comment]
Ah, so definitely not the Fedora kernel. That explains that. Thank you!

**Comment by nikhiljha** [comment]
Appears to be fixed in newest release.
