### ISSUE TITLE
Random mac address

### ISSUE THREAD

**Issue by nas00** [nikhiljha/pp-fedora-sdsetup#54]
The mac address changes after each reboot.

A similar [issue](https://gitlab.com/mobian1/issues/-/issues/17)  was experienced on mobian.

**Comment by Torbuntu** [comment]
Can confirm. 
In the Pine64 matrix channel it was mentioned to be a bug that was fixed:
```
 fixed it on September 27th by updating u-boot to "v2020.10_rc3"
```
I'm not sure which version of u-boot we have in use currently.

**Comment by alh61** [comment]
The new pp-uboot package updates uboot to latest code, and fixes this problem. This issue can be closed.

**Comment by nikhiljha** [comment]
Should've just left this bug in and called it a privacy feature :^)
