### ISSUE TITLE
include Wifiscanner

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#56]
freshly build for Pinephone 

https://github.com/Cyborgscode/wifiscanner

the default image should contain:

tar
strace 
wireless-tools
nautilus
gedit
gnome-calc
gnome-maps
gnome-weather
geary ( works only in gnome-x11 landscape mode , it's ui is depending on a 16:9 big screen )
gnome-systemmonitor
hydrapaper
pavucontrol
paprefs
shotwell ( not yet, has a image render bug atm )
mpv
qmmp
gnome-extensions

Also the default sshd.conf should contain the X11forwarding, as you can than work with apps via "ssh -Y -C pine@ip " on your mainscreen.

**Comment by nullr0ute** [comment]
> https://github.com/Cyborgscode/wifiscanner

Why?
 
> the default image should contain:

Most of these are opinions.

> wireless-tools

Why? It's long dead upstream and is replaced by iw and related tools, what does it provide?

> Also the default sshd.conf should contain the X11forwarding, as you can than work with apps via "ssh -Y -C pine@ip " on your mainscreen.

Again this is a personal preference.

**Comment by Cyborgscode** [comment]
You need wireless-tools for iwlist , which is a dependency for wifiscanner. 

"opinions" .. yes, from an enthusastic linux tablet fanatic :) 
Thats why i want a working gnome env, with the best extentions for touch devices. unfortunatly, the actual gnome-shell on the phone, does not support all extentions yet.

**Comment by nullr0ute** [comment]
> You need wireless-tools for iwlist , which is a dependency for wifiscanner.

wifiscanner should move to the iw command as iwlist doesn't even return all APs anymore and will soon be going away in Fedora altogether, it was only obsoleted by iw around 13+ years ago.

**Comment by Cyborgscode** [comment]
not a big problem. Put a watch on the project and i upload version for iw asaic.

**Comment by nikhiljha** [comment]
I'm not sure what Wi-Fi scanner does, but you're always welcome to package it yourself- it just won't be included in the base distribution. Once the project is mature enough you could also [become a package maintainer](https://fedoraproject.org/wiki/Join_the_package_collection_maintainers) and get it into Fedora upstream.

Thanks :)
