### ISSUE TITLE
proximity sensor always on

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#57]
The powerled is blinking invisible in infrared. You can see it, when you put the pine infront of a running Webcam.

![Webcam-1606851805](https://user-images.githubusercontent.com/8317797/100788885-ff78da80-3415-11eb-90e5-191576272696.png)

**Comment by nikhiljha** [comment]
👀 this is pretty crazy

**Comment by Torbuntu** [comment]
Is that the proximity sensor?

**Comment by nikhiljha** [comment]
Oh yeah, I forgot the pinephone had one

Probably shouldn’t be happening when not in a call though, so I’ll leave this open

**Comment by Torbuntu** [comment]
![20201201_183255](https://user-images.githubusercontent.com/17347324/100812915-c59ed880-3403-11eb-9e21-384074516bf9.jpg)

Yeah it has got to be some sensor. Here is a shot with a blue sms notification to the left of the infrared "beacon"

**Comment by Cyborgscode** [comment]
Small update: in Manjaro it's always blinking too and it's wrongfully blanking the screen, if "something" gets near it. It's blinking is slower.. ( takes less energy ). The proximity alarm is .. an easy pray to a false-positive-situation .. I'm not even near it, and it's staring to flash the screen in and out. 

In Fedora: its better, because if does not blank the screen out. Can't check that for calls, as the calls do not work: No nconnection to pulseaudio.

**Comment by Torbuntu** [comment]
Calls currently do not blank the screen during proximity.

**Comment by Cyborgscode** [comment]
seems to work now
