### ISSUE TITLE
Calls does not connect to pulseaudio

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#59]
System is up2date (-mesa)

Calls get out, connect to the other phone, but "calls" itself does not connect to pulseaudio.

Logfile:

**Comment by Cyborgscode** [comment]
The unit systemd-localed.service has successfully entered the 'dead' state.
Dez 02 17:08:43 fedorapine ModemManager[335]: <warn>  [modem0] unexpected incoming call to number 'n/a' reported in call list: state active
Dez 02 17:08:43 fedorapine ModemManager[335]: <warn>  [modem0] unexpected incoming call to number 'n/a' reported in call list: state active
Dez 02 17:08:45 fedorapine ModemManager[335]: <warn>  [modem0] unexpected incoming call to number 'n/a' reported in call list: state active
Dez 02 17:08:45 fedorapine ModemManager[335]: <warn>  [modem0] unexpected incoming call to number 'n/a' reported in call list: state active
Dez 02 17:08:47 fedorapine ModemManager[335]: <info>  [modem0/call0] call state changed: dialing -> active (unknown)
Dez 02 17:08:47 fedorapine ModemManager[335]: <warn>  [modem0] unexpected incoming call to number 'n/a' reported in call list: state active
Dez 02 17:08:47 fedorapine ModemManager[335]: <warn>  [modem0] unexpected incoming call to number 'n/a' reported in call list: state active
Dez 02 17:08:48 fedorapine systemd-coredump[1477]: [🡕] Process 1283 (callaudiod) of user 1000 dumped core.
                                                   
                                                   Stack trace of thread 1283:
                                                   #0  0x000000555f5e546c set_output_port (callaudiod + 0x546c)
                                                   #1  0x0000007f912d30d8 context_get_sink_info_callback.lto_priv.0 (libpulse.so.0 + 0x1a0d8)
                                                   #2  0x0000007f90ec3c3c run_action (libpulsecommon-14.0.so + 0x42c3c)
                                                   #3  0x0000007f90ec45e0 pa_pdispatch_run (libpulsecommon-14.0.so + 0x435e0)
                                                   #4  0x0000007f912cc18c pstream_packet_callback (libpulse.so.0 + 0x1318c)
                                                   #5  0x0000007f90ec9294 do_read (libpulsecommon-14.0.so + 0x48294)
                                                   #6  0x0000007f90ecab64 do_pstream_read_write (libpulsecommon-14.0.so + 0x49b64)
                                                   #7  0x0000007f90ecaf1c srb_callback (libpulsecommon-14.0.so + 0x49f1c)
                                                   #8  0x0000007f90ec995c srbchannel_rwloop (libpulsecommon-14.0.so + 0x4895c)
                                                   #9  0x0000007f9129a618 dispatch_func (libpulse-mainloop-glib.so.0 + 0x2618)
                                                   #10 0x0000007f915734f0 g_main_context_dispatch (libglib-2.0.so.0 + 0x564f0)
                                                   #11 0x0000007f915ca0b4 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xad0b4)
                                                   #12 0x0000007f91572ba0 g_main_loop_run (libglib-2.0.so.0 + 0x55ba0)
                                                   #13 0x000000555f5e2f10 main (callaudiod + 0x2f10)
                                                   #14 0x0000007f91136bc4 __libc_start_main (libc.so.6 + 0x24bc4)
                                                   #15 0x000000555f5e2f78 _start (callaudiod + 0x2f78)
                                                   
                                                   Stack trace of thread 1286:
                                                   #0  0x0000007f911e3640 __poll (libc.so.6 + 0xd1640)
                                                   #1  0x0000007f915ca050 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xad050)
                                                   #2  0x0000007f91572ba0 g_main_loop_run (libglib-2.0.so.0 + 0x55ba0)
                                                   #3  0x0000007f91441718 gdbus_shared_thread_func.lto_priv.0 (libgio-2.0.so.0 + 0x127718)
                                                   #4  0x0000007f915a3658 g_thread_proxy (libglib-2.0.so.0 + 0x86658)
                                                   #5  0x0000007f910430c8 start_thread (libpthread.so.0 + 0x80c8)
                                                   #6  0x0000007f911edd9c thread_start (libc.so.6 + 0xdbd9c)
                                                   
                                                   Stack trace of thread 1284:
                                                   #0  0x0000007f911e3640 __poll (libc.so.6 + 0xd1640)
                                                   #1  0x0000007f915ca050 g_main_context_iterate.constprop.0 (libglib-2.0.so.0 + 0xad050)
                                                   #2  0x0000007f9157042c g_main_context_iteration (libglib-2.0.so.0 + 0x5342c)
                                                   #3  0x0000007f91572324 glib_worker_main (libglib-2.0.so.0 + 0x55324)
                                                   #4  0x0000007f915a3658 g_thread_proxy (libglib-2.0.so.0 + 0x86658)
                                                   #5  0x0000007f910430c8 start_thread (libpthread.so.0 + 0x80c8)
                                                   #6  0x0000007f911edd9c thread_start (libc.so.6 + 0xdbd9c)
░░ Subject: Speicherabbild für Prozess 1283 (callaudiod) generiert
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ Documentation: man:core(5)

**Comment by Torbuntu** [comment]
The core dump has been fixed upstream but has not yet been made into a release (callaudiod).

**Comment by Cyborgscode** [comment]
FIXED with latest image.
