### ISSUE TITLE
Questions about contributions

### ISSUE THREAD

**Issue by FreedomBen** [nikhiljha/pp-fedora-sdsetup#6]
Hi @nikhiljha !

I'm a fellow Fedora user and Pine Phone owner, looking to marry the two together.  I'm going to give your scripts a try.  I've been running Fedora on my desktop now for many years and I'm excited to potentially get it going on the phone.

First question.  You mention that you haven't done a ton of bash; are you open to PRs that refactor parts of your scripts?  I'm quite experienced in bash so can definitely help follow best practice.  If you don't want me to that's totally fine, I just hope to know before I invest any time in to it :smile:  I'd love to get it to a point where it's just a couple of commands, similar to PostMarket OS `pmbootstrap`.

Second question:  I found what looks like a mirror of this repo on gitlab.  Which one is the primary?

Thanks,

Ben

**Comment by nikhiljha** [comment]
Hi! Thanks for the questions.

Yes, I would definitely be open to that PR. That said- I'm currently working on moving everything into upstream Fedora, so hopefully a large part of this script will soon be handled by arm-image-installer: https://pagure.io/arm-image-installer

This is the primary repository, for some reason github is more discoverable for people.

If you're interested in helping out, please join one of our chats (all linked together):

    Telegram: https://t.me/fedoraphone
    Discord: https://discord.gg/NV4U45G
    IRC: #fedora-phone on Freenode (not recommended, images and video aren't bridged)
    Matrix: #fedora-mobile:matrix.org

Thanks!
