### ISSUE TITLE
Gnome-Shell-Extensions: missing unzip package denies installation

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#60]
It's necessary to have the unzip package installed, when you wanne install gnome-extensions via the gnome website. Not for all, but for most of them.

I suggest to include it in the base image.

**Comment by Torbuntu** [comment]
Is this for when using GNOME? I didn't think extensions are available for Phosh.

**Comment by Cyborgscode** [comment]
# "Is this for when using GNOME? I didn't think extensions are available for Phosh." Torbuntu

Exactly. Phosh is nice and one time it will be a good solution for  pone desktop. I have decided to run Main Gnome, as it's native touch experience is great (and the windows are matching on screen ;) )
