### ISSUE TITLE
megapixel causing 100% cpu core load on xOrg process

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#65]
Thanks for the Update.. cams start to work now, but 

1) megapixel overloads the Xorg process with inperformant paint(or else) requests. Which makes the whole system inresponsive. Xorg and Megapixels run each with 100% on one core and when Xorg does this, the system uis slow down.

2) it does not reflect if the device is portray or landscape mode. It's always in portray mode.

Software versions: 4. of Dec. 15:00 CET.   ( - gnome-shell, bind-libs, mutter, mesa-libs )

**Comment by nikhiljha** [comment]
This sounds like an upstream bug, so I'm going to close the issue here.
