### ISSUE TITLE
kernel 5.10rc6 does not contain a needed mod

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#67]
[root@fedorapine Downloads]# sensors
No sensors found!
Make sure you loaded all the kernel drivers you need.
Try sensors-detect to find out which these are.
[root@fedorapine Downloads]# sensors-detect
# sensors-detect version 3.6.0
**# Kernel: 5.10.0-rc6-00340-gd11aa97d2831 aarch64**
# Cannot show processor info on aarch64 architecture.

This program will help you determine which kernel modules you need
to load to use lm_sensors most effectively. It is generally safe
and recommended to accept the default answers to all questions,
unless you know what you're doing.

Some south bridges, CPUs or memory controllers contain embedded sensors.
Do you want to scan for them? This is totally safe. (YES/no): y
**modprobe: FATAL: Module cpuid not found in directory /lib/modules/5.10.0-rc6-00340-gd11aa97d2831**
Failed to load module cpuid.

**Comment by alh61** [comment]
You write this does not work on kernel 5.10-rc6
Does this imply, that you have tested it on all previous kernels, and it was working there ?
We don't include 'sensors' - which means this it completely untested by us - and beyond the scope of our image.
