### ISSUE TITLE
megapixels crahsing on cam switch

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#68]
Megapixels is working better in PHOSH mode.

But it crashes when switching cams:

Dez 04 16:07:51 fedorapine kernel: sun6i-csi 1cb0000.csi: Unsupported pixformat: 0x31384142 with mbus code: 0x2006!

**Comment by Cyborgscode** [comment]
0.13.1-1 : does no longer crash, but stops working :)  Also, switching between Shutter and ISO  no crashes the app. Still no saturation or half real color reproduction. 

Overall: no improvement between 0.12 and 0.13

**Comment by alh61** [comment]
This problem Is gone with release 14 and 15 I believe.

**Comment by Cyborgscode** [comment]
gone
