### ISSUE TITLE
lightdm does not go into suspend

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#72]
If the device is locked with "dm-tool lock" the  numeric pad appears. If you wait long enough the display is turned off.
But the device is still powered and consumes 1.5W  

This 1.5W will eat the battery. 

Conclusion: 

LightDM needs a patch to call systemd-suspend or similar to send the hardware to sleep.

(If one is on it, it shall display the actual time too.)

FYI:  0.5 W is consumed by a dark display itself

**Comment by nikhiljha** [comment]
lightdm is no longer used, closing
