### ISSUE TITLE
Supertuxkart: openGL ES 3 outdated?

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#79]
supertuxkart complains about an outdated OpenGL ES 3 driver ...? 

It also had no sound on first run. After rebooting sound works.

Game supports touch, so it's worth investigating the OpenGL ES 3 Driver issue imho.

**Comment by Torbuntu** [comment]
The PinePhone Mali 400 does *not* support OpenGL ES 3. 
https://en.wikipedia.org/wiki/Mali_(GPU)

**Comment by nikhiljha** [comment]
Also this probably isn't the right issue tracker to discuss bugs with individual applications. I'm sure a *lot* of applications are broken for reasons way outside our control.
