### ISSUE TITLE
Time and Date Setup Issues

### ISSUE THREAD

**Issue by noeman5** [nikhiljha/pp-fedora-sdsetup#8]
When setting up my newly downloaded version (Rawhide 04), I was unable to use the application for setting date and time.  The application window is not scaled properly for the PinePhone screen, thus most of North and South America are off of the screen and auto-rotation does not work, so I can't use the app in landscape mode to correct for this.  I was forced to manually set the time, which wasn't a problem, but thought you should know about the screen issue.  Oh, and your installation instructions are outdated.  Gparted has removed the resize command starting with version 3.0.

**Comment by nikhiljha** [comment]
> Gparted has removed the resize command starting with version 3.0.

It's still there within the interactive version of parted. See https://github.com/nikhiljha/pp-fedora-sdsetup/issues/12#issuecomment-636182234.

As for scaling issues, yes I'm aware but it needs to be fixed in upstream phosh. :)

**Comment by nikhiljha** [comment]
As a workaround, you can (must be in this order)...

- open settings -> date and time
- manually rotate the screen
- tap your timezone
- close the keyboard
- tap where on the map you are
- open the app drawer and close the "date and time" window

**Comment by alh61** [comment]
could we close this ? I doubt we have any issues like this with latest build ?
