### ISSUE TITLE
 sun8i-codec-aif2 sample rate (8000 Hz) conflicts with other audio streams

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#82]
While booting you get a lot of these messages:

Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: sun8i-codec-aif2 sample rate (8000 Hz) conflicts with other audio streams
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: ASoC: error at snd_soc_dai_hw_params on sun8i-codec-aif2: -16
Dez 13 17:52:38 fedorapine kernel: asoc-simple-card sound: ASoC: PRE_PMU: ec25-sun8i-codec-aif2-playback event failed: -16
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: sun8i-codec-aif2 sample rate (8000 Hz) conflicts with other audio streams
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: ASoC: error at snd_soc_dai_hw_params on sun8i-codec-aif2: -16
Dez 13 17:52:38 fedorapine kernel: asoc-simple-card sound: ASoC: PRE_PMU: ec25-sun8i-codec-aif2-playback event failed: -16
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: sun8i-codec-aif2 sample rate (8000 Hz) conflicts with other audio streams
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: ASoC: error at snd_soc_dai_hw_params on sun8i-codec-aif2: -16
Dez 13 17:52:38 fedorapine kernel: asoc-simple-card sound: ASoC: PRE_PMU: ec25-sun8i-codec-aif2-capture event failed: -16
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: sun8i-codec-aif2 sample rate (8000 Hz) conflicts with other audio streams
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: ASoC: error at snd_soc_dai_hw_params on sun8i-codec-aif2: -16
Dez 13 17:52:38 fedorapine kernel: asoc-simple-card sound: ASoC: PRE_PMU: ec25-sun8i-codec-aif2-capture event failed: -16
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: sun8i-codec-aif2 sample rate (8000 Hz) conflicts with other audio streams
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: ASoC: error at snd_soc_dai_hw_params on sun8i-codec-aif2: -16
Dez 13 17:52:38 fedorapine kernel: asoc-simple-card sound: ASoC: PRE_PMU: ec25-sun8i-codec-aif2-capture event failed: -16
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: sun8i-codec-aif2 sample rate (8000 Hz) conflicts with other audio streams
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: ASoC: error at snd_soc_dai_hw_params on sun8i-codec-aif2: -16
Dez 13 17:52:38 fedorapine kernel: asoc-simple-card sound: ASoC: PRE_PMU: ec25-sun8i-codec-aif2-playback event failed: -16
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: sun8i-codec-aif2 sample rate (8000 Hz) conflicts with other audio streams
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: ASoC: error at snd_soc_dai_hw_params on sun8i-codec-aif2: -16
Dez 13 17:52:38 fedorapine kernel: asoc-simple-card sound: ASoC: PRE_PMU: ec25-sun8i-codec-aif2-playback event failed: -16
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: sun8i-codec-aif2 sample rate (8000 Hz) conflicts with other audio streams
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: ASoC: error at snd_soc_dai_hw_params on sun8i-codec-aif2: -16
Dez 13 17:52:38 fedorapine kernel: asoc-simple-card sound: ASoC: PRE_PMU: ec25-sun8i-codec-aif2-capture event failed: -16
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: sun8i-codec-aif2 sample rate (8000 Hz) conflicts with other audio streams
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: ASoC: error at snd_soc_dai_hw_params on sun8i-codec-aif2: -16
Dez 13 17:52:38 fedorapine kernel: asoc-simple-card sound: ASoC: PRE_PMU: ec25-sun8i-codec-aif2-playback event failed: -16
Dez 13 17:52:38 fedorapine kernel: sun8i-codec 1c22e00.codec: sun8i-codec-aif2 sample rate (8000 Hz) conflicts with other audio streams
Dez 13 17:52:39 fedorapine kernel: sun8i-codec 1c22e00.codec: ASoC: error at snd_soc_dai_hw_params on sun8i-codec-aif2: -16
Dez 13 17:52:39 fedorapine kernel: asoc-simple-card sound: ASoC: PRE_PMU: ec25-sun8i-codec-aif2-playback event failed: -16
Dez 13 17:52:39 fedorapine kernel: sun8i-codec 1c22e00.codec: sun8i-codec-aif2 sample rate (8000 Hz) conflicts with other audio streams
Dez 13 17:52:39 fedorapine kernel: sun8i-codec 1c22e00.codec: ASoC: error at snd_soc_dai_hw_params on sun8i-codec-aif2: -16

**Comment by alh61** [comment]
there have been a lot of audio updates the last 4 months. Do you still see this ?

**Comment by Cyborgscode** [comment]
we still have a lot of bug messages on sun8i , but they differ now. As audio works well, i think we can close this for now.
