### ISSUE TITLE
Lockscreen too sensitiv => never suspends again

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#87]
RealLife-Testresult: 

( a) the powerbutton is a mechanical fail, because it gets easily activated if phone is carried in trousers. )

b) Worse is only the sensitivity of the touchscreen, which leads to a never closing lockscreen, because every few seconds a ghost tip is recognized and the timeout timer is set back to 0.

I strongly suggest to lower the sensitivity of the touchscreen device, while in lockscreen. If the screen is successfully unlocked, it can be set back to normal. Also the timeout needs to cut to 5-10 seconds, until the device is send back to "suspend" and not only turning of the screen.  

"Special Usecase RL: do not suspend if multimedia is played back."

If someone points me to the correct components, I will rewrite and test it untill it's useable.

**Comment by alh61** [comment]
A: Talk to Pine64 about that - it has nothing to do with Fedora or software

B: Yes, when screen is blanked, the digitizer is supposed to be turned off - which we currently do not do. Patches welcome.

> "Special Usecase RL: do not suspend if multimedia is played back."
This is completely up to the software itself, to tell the kernel, that is should not allow suspend, while it is running. Again, that has nothing to do with our image.

**Comment by Cyborgscode** [comment]
With the latest changes to phosh unlocker, problem got way better. The same trip with the same outfit did not lead to ghostclicks afaik. For now, closing it.
