### ISSUE TITLE
CRUST implementation

### ISSUE THREAD

**Issue by TimotheeLF** [nikhiljha/pp-fedora-sdsetup#9]
Is there any plan to implement CRUST to get better battery life?

https://github.com/crust-firmware/crust
https://www.reddit.com/r/PINE64official/comments/g1pldk/battery_life_on_the_pinephone_is_starting_to_look/

**Comment by nikhiljha** [comment]
This project uses https://megous.com/git/u-boot, and https://megous.com/git/linux. If both of those gain support for CRUST, these images will as well.

As for upstream Fedora, that's less likely until CRUST gets into mainline Linux and u-boot, which will take a while.

**Comment by alh61** [comment]
We are testing crust now with very good results - up to 20 hours in standby.

**Comment by nullr0ute** [comment]
> As for upstream Fedora, that's less likely until CRUST gets into mainline Linux and u-boot, which will take a while.

Actually it's got nothing to do with the kernel, crust purely deals with firmware, the kernel interactions with ATF/PSCI which in turn talks to crust. There's patches under review to support it in the firmware bits upstream.

**Comment by alh61** [comment]
Since Crust was implemented into our image some time ago, I think we can close this ticket.
