### ISSUE TITLE
Make a u-boot package instead of using a binary file.

### ISSUE THREAD

**Issue by kvuj** [nikhiljha/pp-fedora-sdsetup#91]
~~Here is postmarketOS' [APKBUILD](https://gitlab.com/postmarketOS/pmaports/-/tree/master/temp/u-boot-pinephone).~~

~~Both of the patch will be removed as soon as this [MR](https://gitlab.com/postmarketOS/pmaports/-/merge_requests/1846) gets merged, so we can ignore them and just use a recent version.~~

EDIT: NVM, seems like [it's packaged](https://copr.fedorainfracloud.org/coprs/njha/mobile/package/pp-uboot/), I was just wondering since I saw that weird uboot [readme](https://github.com/nikhiljha/pp-fedora-sdsetup/blob/master/uboot/README).

**Comment by alh61** [comment]
indeed it is packaged in pp-uboot. Pls close this ticket.
