### ISSUE TITLE
No Sound anymore

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#94]
Since 1.2.2021 there is no sound anymore, no matter the source.

Pulseaudio Control shows the audio playing on sinks, but no combination of devices produces any sound.

"pulseaudio" is also gone.

**Comment by Torbuntu** [comment]
Fedora is moving to pipewire. The first time you boot you may need to go to settings and switch the profiles manually. Not sure why that was the case but it worked. I only had to do that once.

**Comment by Cyborgscode** [comment]
Reinstalling with the new Image of 31.1.2021 fixed this issue, but opened new ones ;)
