### ISSUE TITLE
crash with megapixels 5.11.0-rc7

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#97]
[  338.128731] cma: cma_alloc: alloc failed, req-size: 1231 pages, ret: -12
[  338.128790] ------------[ cut here ]------------
[  338.128793] WARNING: CPU: 1 PID: 1452 at mm/page_alloc.c:4979 __alloc_pages_nodemask+0x62c/0xc60
[  338.128823] Modules linked in: snd_seq_dummy snd_hrtimer option qmi_wwan usb_wwan cdc_wdm usbserial usbnet mii snd_soc_hdmi_codec mousedev 8723cs(C) aes_ce_blk crypto_simd aes_ce_cipher crct10dif_ce ghash_ce gf128mul sha2_ce sha256_arm64 st_magn_i2c st_sensors_i2c sha1_ce inv_mpu6050_i2c sunxi_cedrus(C) st_magn lima cfg80211 inv_mpu6050 st_sensors industrialio_triggered_buffer sun8i_rotate sunxi kfifo_buf sun6i_csi gpu_sched sun8i_di sun4i_i2s phy_generic ehci_platform ohci_platform sun50i_codec_analog sun8i_adda_pr_regmap sun8i_codec dw_hdmi_i2s_audio musb_hdrc v4l2_mem2mem snd_soc_simple_card snd_soc_simple_card_utils snd_soc_ec25 snd_soc_bt_sco snd_soc_simple_amplifier hci_uart btrtl ehci_hcd stk3310 bluetooth snd_soc_core videobuf2_dma_contig ohci_hcd anx7688 goodix snd_pcm_dmaengine gc2145 regmap_i2c snd_seq ecdh_generic ecc modem_power rfkill snd_seq_device udc_core snd_pcm ov5640 videobuf2_memops videobuf2_v4l2 sun8i_ce leds_sgm3140 usbcore videobuf2_common v4l2_fwnode
[  338.129062]  v4l2_flash_led_class snd_timer videodev crypto_engine snd mc soundcore fuse zram autofs4
[  338.129097] CPU: 1 PID: 1452 Comm: megapixels Tainted: G         C        5.11.0-rc7-00312-g2ad7347a7163 #23
[  338.129106] Hardware name: Pine64 PinePhone (1.2) (DT)
[  338.129111] pstate: 20000005 (nzCv daif -PAN -UAO -TCO BTYPE=--)
[  338.129119] pc : __alloc_pages_nodemask+0x62c/0xc60
[  338.129129] lr : __dma_direct_alloc_pages+0x130/0x184
[  338.129141] sp : ffffffc01560b890
[  338.129145] x29: ffffffc01560b890 x28: ffffffc01560bbd0 
[  338.129154] x27: 0000000000000001 x26: ffffff8025e28860 
[  338.129163] x25: ffffff8009038a98 x24: ffffff80011c6010 
[  338.129172] x23: ffffffc0100a8c68 x22: 00000000004cf000 
[  338.129181] x21: 0000000000000cc0 x20: 00000000004cf000 
[  338.129189] x19: ffffff80011c6010 x18: 00000000fffffffc 
[  338.129198] x17: 0000000000000000 x16: 0000000000000000 
[  338.129206] x15: 0000000000000020 x14: ffffffffffffffff 
[  338.129215] x13: ffffffc010c3dc88 x12: 000000000000106b 
[  338.129223] x11: 0000000000000579 x10: ffffffc010c95c88 
[  338.129232] x9 : 00000000fffff000 x8 : 0000000000000000 
[  338.129240] x7 : ffffffc010c95c88 x6 : 0000000000000001 
[  338.129249] x5 : 0000000000000000 x4 : 000000000000003f 
[  338.129257] x3 : 0000000000000000 x2 : 0000000000000000 
[  338.129265] x1 : 000000000000000b x0 : 0000000000000cc0 
[  338.129274] Call trace:
[  338.129278]  __alloc_pages_nodemask+0x62c/0xc60
[  338.129288]  __dma_direct_alloc_pages+0x130/0x184
[  338.129295]  dma_direct_alloc+0x60/0x2e0
[  338.129303]  dma_alloc_attrs+0x68/0xc0
[  338.129311]  vb2_dc_alloc+0x64/0x124 [videobuf2_dma_contig]
[  338.129325]  __vb2_queue_alloc+0x184/0x44c [videobuf2_common]
[  338.129338]  vb2_core_reqbufs+0x210/0x3ec [videobuf2_common]
[  338.129347]  vb2_ioctl_reqbufs+0x7c/0xb0 [videobuf2_v4l2]
[  338.129358]  v4l_reqbufs+0x48/0x60 [videodev]
[  338.129393]  __video_do_ioctl+0x170/0x3b4 [videodev]
[  338.129413]  video_usercopy+0x18c/0x5b0 [videodev]
[  338.129434]  video_ioctl2+0x14/0x20 [videodev]
[  338.129454]  v4l2_ioctl+0x3c/0x60 [videodev]
[  338.129473]  __arm64_sys_ioctl+0xac/0xd0
[  338.129482]  el0_svc_common.constprop.0+0x5c/0x114
[  338.129494]  do_el0_svc+0x18/0x20
[  338.129501]  el0_svc+0x10/0x1c
[  338.129512]  el0_sync_handler+0xa8/0xac
[  338.129520]  el0_sync+0x140/0x180
[  338.129528] ---[ end trace 53ffc91d7b808c6f ]---
[  338.129541] sun6i-csi 1cb0000.csi: dma_alloc_coherent of size 5042176 failed
[root@fedorapine ~]#

**Comment by nikhiljha** [comment]
this should be tracked upstream, closing for now
