### ISSUE TITLE
GPS working in Gnome, but not with Phosh

### ISSUE THREAD

**Issue by Cyborgscode** [nikhiljha/pp-fedora-sdsetup#99]
gnome-maps-3.38.3-2.fc34
gnome-shell-40.0~alpha.1.1-4.20210202git9ce666ac1.fc34 ( worked with 3.38 also )
phosh 0.8.0

The GPS locationbutton works in a pure gnome-shell, but not with phosh as manager.

Conclusion:  in general GPS working with 5.11.0rc7
I suggest to open a pure.sm bug for it.

**Comment by Baggypants** [comment]
It's because geoclue demands an agent to be running and phosh doesn't provide one

https://source.puri.sm/Librem5/phosh/-/issues/153

**Comment by Baggypants** [comment]
Workaround. Create a systemd user unit file to start the agent at boot

```bash
cd .config/systemd/user
cat << EOF >  geo-agent.service
[Unit]
Description=GeoClue agent to authenticate desktop apps to geoclue
Documentation=https://github.com/nikhiljha/pp-fedora-sdsetup/issues/99
After=display-manager.service

[Service]
ExecStart=/usr/libexec/geoclue-2.0/demos/agent
Restart=always
RestartSec=5s
[Install]
WantedBy=default.target
EOF
systemctl --user daemon-reload
systemctl --user enable --now geo-agent
```

**Comment by agx** [comment]
phosh provides a geoclue agent since 0.10.0. I rather assume your geoclue.conf doesn't allow phosh.

**Comment by agx** [comment]
Relevant upstream commit https://gitlab.freedesktop.org/geoclue/geoclue/-/commit/a9aea6a4948e2ff9ec5ff066cf20dac069c0d3a0

**Comment by Cyborgscode** [comment]
fixed by ...
- allowing geoclue via polkitd to access  modemmanager objects.
- sending extra3gr.bin (agps) to modemmanager to speed up satellite location
- adding systemd service to start agps script.

RPM available: 

http://static.bloggt-in-braunschweig.de/modemmanager-agps-1-1.aarch64.rpm
